# Generated by Django 4.2.7 on 2023-11-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Const_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='const_projects_img')),
                ('plane', models.FileField(upload_to='plane_img')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('type', models.CharField(max_length=10000, null=True)),
                ('date', models.IntegerField(max_length=1000, null=True)),
                ('square', models.CharField(max_length=1000, null=True)),
                ('place', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('team', models.CharField(max_length=10000, null=True)),
                ('workType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.worktype')),
            ],
        ),
    ]
