# Generated by Django 4.2.7 on 2023-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='const_projects',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
