# Generated by Django 4.2.7 on 2023-11-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_const_projects_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='const_projects',
            name='workType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.worktype'),
        ),
    ]
