# Generated by Django 4.2.7 on 2023-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_images_imagesss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesss',
            name='image',
        ),
        migrations.AddField(
            model_name='imagesss',
            name='photo',
            field=models.ImageField(null=True, upload_to='Imagesss'),
        ),
        migrations.RemoveField(
            model_name='const_projects',
            name='images',
        ),
        migrations.AddField(
            model_name='const_projects',
            name='images',
            field=models.ManyToManyField(to='projects.imagesss'),
        ),
    ]
