# Generated by Django 4.2.7 on 2023-11-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_images_delete_imagesss_alter_const_projects_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Imagesss',
        ),
    ]
