# Generated by Django 4.2.7 on 2023-11-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_images_imagesss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagesss',
            new_name='Images',
        ),
    ]
