# Generated by Django 4.2.7 on 2023-11-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_imagesss_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Photos',
        ),
    ]
