# Generated by Django 4.2.7 on 2023-11-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_images_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const_projects',
            old_name='images',
            new_name='imagesss',
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(null=True, upload_to='Const_images'),
        ),
    ]
