# Generated by Django 4.2.7 on 2023-11-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_images_const_projects_imagesss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='const_projects',
            name='imagesss',
        ),
    ]
