# Generated by Django 4.2.7 on 2023-11-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_const_projects_imagesss'),
    ]

    operations = [
        migrations.AddField(
            model_name='const_projects',
            name='images',
            field=models.ManyToManyField(to='projects.photos'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(null=True, upload_to='Const_photos'),
        ),
    ]
